#!/bin/bash

pushd `dirname $0` > /dev/null
SCRIPT_PATH=`pwd -P`

if [ -z "$JAVA_HOME" ]; then
	JAVA_HOME=$(/usr/libexec/java_home)
fi

popd > /dev/null

OUTPUT_DIR=/tmp/jdbg-$((RANDOM))

mkdir $OUTPUT_DIR

javac -classpath $JAVA_HOME/lib/tools.jar -d $OUTPUT_DIR $SCRIPT_PATH/src/*.java $SCRIPT_PATH/src/command/*.java

java -classpath $OUTPUT_DIR:$JAVA_HOME/lib/tools.jar jdbg.MainClass $*

rm -R $OUTPUT_DIR
